=== prog-nov/iso20022-doc_projects/ExternalMessages/XML/DTD/ejb/Cartridges/ejb-jar.dtd
<!-- edited with XML Spy v3.0.7 NT (http://www.xmlspy.com) by indu (indu) -->
<!ELEMENT assembly-descriptor (security-role*, method-permission*, container-transaction*)>
<!ELEMENT cmp-field (description?, field-name)>
<!ELEMENT container-transaction (description?, method+, trans-attribute)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT display-name (#PCDATA)>
<!ELEMENT ejb-class (#PCDATA)>
<!ELEMENT ejb-client-jar (#PCDATA)>
<!ELEMENT ejb-jar (description?, display-name?, small-icon?, large-icon?, enterprise-beans, assembly-descriptor?, ejb-client-jar?)>
<!ELEMENT ejb-link (#PCDATA)>
<!ELEMENT ejb-name (#PCDATA)>
<!ELEMENT ejb-ref (description?, ejb-ref-name, ejb-ref-type, home, remote, ejb-link?)>
<!ELEMENT ejb-ref-name (#PCDATA)>
<!ELEMENT ejb-ref-type (#PCDATA)>
<!ELEMENT enterprise-beans (session* | entity*)*>
<!ELEMENT entity (description?, display-name?, small-icon?, large-icon?, ejb-name, home, remote, ejb-class, persistence-type, prim-key-class, reentrant, cmp-field*, primkey-field?, env-entry*, ejb-ref*, security-role-ref*, resource-ref*)>
<!ELEMENT env-entry (description?, env-entry-name, env-entry-type, env-entry-value?)>
<!ELEMENT env-entry-name (#PCDATA)>
<!ELEMENT env-entry-type (#PCDATA)>
<!ELEMENT env-entry-value (#PCDATA)>
<!ELEMENT field-name (#PCDATA)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT large-icon (#PCDATA)>
<!ELEMENT method (description?, ejb-name, method-intf?, method-name, method-params*)>
<!ELEMENT method-intf (#PCDATA)>
<!ELEMENT method-name (#PCDATA)>
<!ELEMENT method-param (#PCDATA)>
<!ELEMENT method-params (method-param*)>
<!ELEMENT method-permission (description?, role-name+, method+)>
<!ELEMENT persistence-type (#PCDATA)>
<!ELEMENT prim-key-class (#PCDATA)>
<!ELEMENT primkey-field (#PCDATA)>
<!ELEMENT reentrant (#PCDATA)>
<!ELEMENT remote (#PCDATA)>
<!ELEMENT res-auth (#PCDATA)>
<!ELEMENT res-ref-name (#PCDATA)>
<!ELEMENT res-type (#PCDATA)>
<!ELEMENT resource-ref (description?, res-ref-name, res-type, res-auth)>
<!ELEMENT role-link (#PCDATA)>
<!ELEMENT role-name (#PCDATA)>
<!ELEMENT security-role (description?, role-name)>
<!ELEMENT security-role-ref (description?, role-name, role-link?)>
<!ELEMENT session-type (#PCDATA)>
<!ELEMENT session (description?, display-name?, small-icon?, large-icon?, ejb-name, home, remote, ejb-class, session-type, transaction-type, env-entry*, ejb-ref*, security-role-ref*, resource-ref*)>
<!ELEMENT small-icon (#PCDATA)>
<!ELEMENT transaction-type (#PCDATA)>
<!ELEMENT trans-attribute (#PCDATA)>
<!ELEMENT ejbdtd (ejbbody)>
<!ELEMENT ejbbody (ejb-jar*)>

=== prog-nov/iso20022-doc_projects/ExternalMessages/XML/DTD/Batched/Cartridges/sample/ejb-jar.xml
<?xml version="1.0"?>
<!DOCTYPE ejbdtd SYSTEM "ejb-jar.dtd">
<ejbdtd>
	<ejbbody>
<ejb-jar>
<description>InputXML</description>
<display-name>InputXML</display-name>
<enterprise-beans>
<session>
<display-name>com.tplus.transform.runtime.bean.InputFormatRemote</display-name>
<ejb-name>InputXML</ejb-name>
<home>com.tplus.transform.runtime.bean.InputFormatHome</home>
<remote>com.tplus.transform.runtime.bean.InputFormatRemote</remote>
<ejb-class>NestingInputXMLInputFormatBean</ejb-class>
<session-type>Stateless</session-type>
<transaction-type>Container</transaction-type>
</session>
</enterprise-beans>
<assembly-descriptor>
<container-transaction>
<description>No Description</description>
<method>
<description>No Description</description>
<ejb-name>InputXML</ejb-name>
<method-intf>Remote</method-intf>
<method-name>*</method-name>
</method>
<trans-attribute>Required</trans-attribute>
</container-transaction>
</assembly-descriptor>
</ejb-jar>
	</ejbbody>
</ejbdtd>
